
jms:
  enabled: true
  connection:
    server: amqp://localhost:5672
    vhost: /test
    reconnect-interval: 10000
  listeners:
    - id: queueListener
      type: QUEUE
      topic: command/queue
      bean-name: queueListener
    - id: topicListener
      type: TOPIC
      topic: command/topic
      bean-name: topicListener